services:
  _defaults:
    autoconfigure: true
    autowire: true

  Guave\FormSaveBundle\Controller\:
    resource: ../src/Controller
    public: true

  Guave\FormSaveBundle\Config\Config:
    public: true

  Guave\FormSaveBundle\Migration\FormDataMigration:
    tags:
      - { name: contao.migration, priority: 0 }
